Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'
  config.vm.synced_folder ".", "/files/", :mount_options => ['dmode=774','fmode=775']
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
	sudo apt-get install software-properties-common
	sudo add-apt-repository ppa:deadsnakes/ppa
	sudo apt-get update
	sudo apt-get install -y python3 python3-pip python3-venv python3-dev libpq-dev
	sudo pip3 install psycopg2
	sudo pip3 install Django
  SHELL
end
