Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'
  config.vm.synced_folder ".", "/files/", :mount_options => ['dmode=774','fmode=775']
  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-get install -y python3 python3-pip
	sudo pip3 install psycopg2 django
  SHELL
end